# Generated by Django 5.2 on 2026-01-17 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('github_repo', models.URLField()),
                ('github_branch', models.CharField(default='main', max_length=50)),
                ('remote_path', models.CharField(blank=True, help_text='Если пусто — использовать base_path/slug', max_length=255)),
                ('compose_file', models.CharField(default='docker-compose.prod.yml', help_text='Имя docker-compose файла на сервере', max_length=255)),
                ('price_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_until', models.DateField(blank=True, null=True)),
                ('free_support_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'NEW'), ('deploying', 'DEPLOYING'), ('active', 'ACTIVE'), ('grace', 'GRACE'), ('suspended', 'SUSPENDED'), ('failed', 'FAILED')], default='new', max_length=20)),
                ('last_deploy_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('ssh_user', models.CharField(default='root', max_length=50)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('base_path', models.CharField(default='/srv/projects', help_text='Базовая папка проектов на удалённом сервере', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('running', 'RUNNING'), ('success', 'SUCCESS'), ('failed', 'FAILED')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.server'),
        ),
    ]
