# Generated by Django 5.2 on 2026-01-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='grace_until',
            field=models.DateField(blank=True, help_text='Дата окончания grace-периода (если проект в статусе GRACE)', null=True),
        ),
    ]
